# Vg Scale

## Video Games dataset

## Author : Khaled Alqrainy

## Date : 25-10-2021

In [5]:
import pandas as pd
import numpy as np

In [6]:
df =pd.read_csv('./vgsales.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

## Which company is the most common video game publisher?

In [7]:
most_common_publisher=df.Publisher.mode()[0]
most_common_publisher

'Electronic Arts'

## Whatâ€™s the most common platform?

In [8]:
most_common_platform=df.Platform.mode()[0]
most_common_platform

'DS'

## What about the most common genre?

In [9]:
most_common_genre=df.Genre.mode()[0]
most_common_genre

'Action'

## What are the top 20 highest grossing games?

In [10]:
top_twenty_highest_grossing_games=df[['Name', 'Global_Sales']].head(20)
top_twenty_highest_grossing_games

                                            Name  Global_Sales
0                                     Wii Sports         82.74
1                              Super Mario Bros.         40.24
2                                 Mario Kart Wii         35.82
3                              Wii Sports Resort         33.00
4                       Pokemon Red/Pokemon Blue         31.37
5                                         Tetris         30.26
6                          New Super Mario Bros.         30.01
7                                       Wii Play         29.02
8                      New Super Mario Bros. Wii         28.62
9                                      Duck Hunt         28.31
10                                    Nintendogs         24.76
11                                 Mario Kart DS         23.42
12                   Pokemon Gold/Pokemon Silver         23.10
13                                       Wii Fit         22.72
14                                  Wii Fit Plus         22.00
15                            Kinect Adventures!         21.82
16                            Grand Theft Auto V         21.40
17                 Grand Theft Auto: San Andreas         20.81
18                             Super Mario World         20.61
19  Brain Age: Train Your Brain in Minutes a Day         20.22

## For North American video game sales, whatâ€™s the median?

In [11]:
north_american_median_sales=df.NA_Sales.median()
north_american_median_sales

0.08

* Provide a secondary output showing ten games surrounding the median sales output

    * assume that games with same median value are sorted in descending order

In [20]:
secondary_median = df[ df["NA_Sales"] == north_american_median_sales]
ten_median_na_seller_names =secondary_median.head(10)["Name"]
ten_median_na_seller_names

446                                     Dragon Warrior IV
497           World Soccer Winning Eleven 7 International
1617                               Farming Simulator 2015
1926                            Pro Evolution Soccer 2008
2067    Winning Eleven: Pro Evolution Soccer 2007 (All...
2373                             Phantasy Star Portable 2
2579                                 The Sims 2: Castaway
3186                                       SingStar Queen
3503                                           Top Spin 3
3703                 Sonic & All-Stars Racing Transformed
Name: Name, dtype: object

## For the top-selling game of all time, how many standard deviations above/below the mean are its sales for North America?

In [12]:
ten_median_na_seller_names=(df['NA_Sales'].max()-df['NA_Sales'].mean()) /df['NA_Sales'].std()
ten_median_na_seller_names

50.47898767479108

## The Nintendo Wii seems to have outdone itself with games. How does its average number of sales compare with all of the other platforms?

In [13]:
avg_global = df.Global_Sales.mean() 
avg_global

0.5374406555006628

In [14]:
avg_wii=df[(df['Platform']=='Wii') ].Global_Sales.mean() 
avg_wii

0.6994037735849057

## Come up with 3 more questions that can be answered with this data set.

## what is the last 10 ranks ?

In [15]:
last_10=df.tail(10)
last_10

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16588,16591,Mega Brain Boost,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.0,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.0,0.01
16590,16593,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,2007.0,Role-Playing,Falcom Corporation,0.00,0.00,0.01,0.0,0.01
16591,16594,Myst IV: Revelation,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.0,0.01
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.0,0.01
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.0,0.01

## Sort the games by year.

In [16]:
sort_by_year=df.sort_values(by=['Year'])
sort_by_year

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
6896,6898,Checkers,2600,1980.0,Misc,Atari,0.22,0.01,0.0,0.00,0.24
2669,2671,Boxing,2600,1980.0,Fighting,Activision,0.72,0.04,0.0,0.01,0.77
5366,5368,Freeway,2600,1980.0,Action,Activision,0.32,0.02,0.0,0.00,0.34
1969,1971,Defender,2600,1980.0,Misc,Atari,0.99,0.05,0.0,0.01,1.05
1766,1768,Kaboom!,2600,1980.0,Misc,Activision,1.07,0.07,0.0,0.01,1.15
...,...,...,...,...,...,...,...,...,...,...,...
16307,16310,Freaky Flyers,GC,NaN,Racing,Unknown,0.01,0.00,0.0,0.00,0.01
16327,16330,Inversion,PC,NaN,Shooter,Namco Bandai Games,0.01,0.00,0.0,0.00,0.01
16366,16369,Hakuouki: Shinsengumi Kitan,PS3,NaN,Adventure,Unknown,0.01,0.00,0.0,0.00,0.01
16427,16430,Virtua Quest,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.0,0.00,0.01
16493,16496,The Smurfs,3DS,NaN,Action,Unknown,0.00,0.01,0.0,0.00,0.01

## What is the games in PS2 platform ?

In [17]:
ps2_platform = df[df['Platform']=='PS2']
ps2_platform

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
24,25,Grand Theft Auto: Vice City,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15
28,29,Gran Turismo 3: A-Spec,PS2,2001.0,Racing,Sony Computer Entertainment,6.85,5.09,1.87,1.16,14.98
38,39,Grand Theft Auto III,PS2,2001.0,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10
47,48,Gran Turismo 4,PS2,2004.0,Racing,Sony Computer Entertainment,3.01,0.01,1.10,7.53,11.66
...,...,...,...,...,...,...,...,...,...,...,...
16559,16562,Sugar + Spice! Anoko no Suteki na Nanimokamo,PS2,2008.0,Adventure,Alchemist,0.00,0.00,0.01,0.00,0.01
16561,16564,Kanokon: Esuii,PS2,2008.0,Adventure,5pb,0.00,0.00,0.01,0.00,0.01
16572,16575,Scarlett: Nichijou no Kyoukaisen,PS2,2008.0,Adventure,Kadokawa Shoten,0.00,0.00,0.01,0.00,0.01
16580,16583,Real Rode,PS2,2008.0,Adventure,Kadokawa Shoten,0.00,0.00,0.01,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01

In [18]:

def test():

    def assert_equal(actual,expected):
        assert actual == expected, f"Expected {expected} but got {actual}"

    assert_equal(most_common_publisher, 'Electronic Arts')
    assert_equal(most_common_platform, 'DS')
    assert_equal(most_common_genre, 'Action')
    assert_equal(top_twenty_highest_grossing_games.iloc[0].Name, 'Wii Sports')
    assert_equal(top_twenty_highest_grossing_games.iloc[19].Name, 'Brain Age: Train Your Brain in Minutes a Day')
    assert_equal(north_american_median_sales, 0.08)
    assert_equal(ten_median_na_seller_names, 50.47898767479108)
    assert_equal(avg_global, 0.5374406555006628)
    assert_equal(avg_wii, 0.6994037735849057)
    assert_equal(last_10.iloc[0].Rank,16591)
    assert_equal(ps2_platform.iloc[0].Name,'Grand Theft Auto: San Andreas')
    assert_equal(last_10, 0.6994037735849057)
    
    print("Success!")

test()

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().